### ISSUE TITLE
Use docker for local development

### ISSUE THREAD

**Issue by rubenvdlinde** [nl-design-system/denhaag#353]
As a developer I want to use a docker containerization for local development environment so that I know that the development across multiple development machines does differ (on example node or yarn packages)

### Describe the solution you'd like
I would like a docker compose file to be present in the repository
### Describe alternatives you've considered
NPM and Yarn packages  are currently described by version number In the readme, do this might work with small teams it to “soft” to work in a greater open source ecosystem.

### Additional context
Containerization is a common ground best practice.

### Acceptance criteria
[] A docker compose file for a NPM/Yarn container
[] docker-compose up couses a working container to come up on the developers machine.

### Definition of Ready

To be completed before the issue can be added to backlog.

- [ ] Acceptance criteria are described
- [ ] Any preconditions are described
- [ ] Possible dependence on external experts is mentioned
- [ ] The story must be understandable for the development team
- [ ] Any requirements for accessibility are described

### Definition of Done

To be completed before the issue can be marked as Done.

- [ ] Code exists on master branch
- [ ] Meets acceptance criteria
- [ ] Complies with [the standard of public code](https://standard.publiccode.net/)
- [ ] Story has been sufficiently tested
  - [ ] 90% code coverage
  - [ ] Build completed
  - [ ] Existing tests pass
- [ ] The frontend component complies with [WCAG 2.1 accessibility guidelines](https://www.w3.org/TR/WCAG21/)

**Comment by Robbert** [comment]
If a consistent development environment is the goal, there are alternatives:

- define exact version of Node.js in `.nvmrc`
- define minor version of Node.js and npm in `engines` of `package.json`
- define exact versions for dependencies (and keep it that way using `save-prefix=` in `.npmrc` and using `.npmpackagejsonlintrc.json`)
- install using `yarn --frozen-lockfile`

Docker seems to have a major disadvantage: it is slow to start because `docker-compose up` will likely trigger a `yarn install` and `yarn bootstrap` every time you change a file, which takes quite some time and requires internet access.

@rubenvdlinde Would greatly reducing the risk of differences also work for you?
