### ISSUE TITLE
CSP Headers issues

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/denhaag#492]
Inline styles can be removed by changing the rollup config to extract css. 

Components using Material UI are fixed when MUI is removed and they're made from scratch.

**Comment by mjcarsjens** [comment]
Adding `extract: true` to the global rollup config does indeed extract the CSS to seperate `.css` files instead of inlining it, however it breaks the visual regression tests for the following components: 

- Alert
- BadgeCounter
- Checkbox
- DotIndicator
- FormControlLabel
- FormGroup

We need to further investigate what goes wrong here and fix these issues.

**Comment by bddjong** [comment]
An alternative solution is to stop shipping CSS with the React Components, and instead expect developers to use `@gemeente-denhaag/components-css` to import styles. 

This will be a nuisance when using a single component package, but maybe we should consider dropping support for single component packages. From what I know, they have so far only been used as a workaround for bugs in the `components-react` package.

**Comment by YourivHDenHaag** [comment]
For now this is fixed with nonces.
