### ISSUE TITLE
Refactor Button

### ISSUE THREAD

**Issue by robbieatacato** [nl-design-system/denhaag#561]
### User story

Refactor button component, make sure a BEM and REACT component exist in different files, and make sure the styles don't come from material-design.

**Comment by paulAcato** [comment]
@bddjong , Refactor of the button was assigned to us, i just noticed on the dashboard you did this already on `feature/refactor-buttons` ( https://github.com/nl-design-system/denhaag/commit/2ec286150b0167a5998a45c650343843877abb31 ) am I correct? If so, we can close this issue. Otherwise we need to know what we need to re-scope this issue.

**Comment by paulAcato** [comment]
@bddjong , check i'll close this issue

**Comment by robbieatacato** [comment]
# Documentation and design:
https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=1%3A656
