### ISSUE TITLE
[Bug] Cannot use import statement outside a module

### ISSUE THREAD

**Issue by KoenBrouwer** [nl-design-system/denhaag#942]
Via [Chantalle den Hertog @ GitLab](https://gitlab.com/chantalle_denhertog) working on [this issue](https://gitlab.com/commonground/huishoudboekje/app-new/-/issues/921):

---

# Enable testing a React application with NL Design System Den Haag components

### User story
As a developer I want to be able to use react-testing-library and jest to test my application that uses NL Design System Den Haag components.

### Additional context
At the moment I am using NLDS Den Haag components in my application. Once I try to run some test I get an error with all the components I am importing from the NLDS Den Haag. I've attached a screenshot of the errors that occur.

When I use components only from the NL Design System Utrecht I have no issues and the tests run fine. Therefor I think there seems to be an issue with the Den Haag components.

![afbeelding](https://user-images.githubusercontent.com/3260168/166454251-4a67b99f-e4a1-4bd2-ad95-8e28cbf7b74a.png)

**Comment by mjcarsjens** [comment]
@bddjong this issue is the result of us exporting the packages as ESM modules in the library which do not work out of the box with jest. This specific issue could be solved by implementing our CommonJS PR (https://github.com/nl-design-system/denhaag/pull/918) for all packages. As stated in the PR we currently only implemented this for the PDS component due to the fact that this would require some more testing to add this to the entire library, but I guess now is as good a moment as any to add this. I'll look into this and hopefully it won't cause any issues and will be a quick fix :)
